// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgxguilkvdilgwoheive.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneGd1aWxrdmRpbGd3b2hlaXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjA4MDcsImV4cCI6MjA1NzQzNjgwN30.gu3CsojrHQR4bWjmzwacPubpqGsUgHCjAJ6aFqVfubw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);